#include "app_translator.h"

#include <utility>

AppTranslator::AppTranslator(QObject *parent) : QTranslator(parent)
{
    const std::pair<const char *, const char *> entries[] = {
        {"File", "文件"}, {"Open…", "打开…"}, {"Save As…", "另存为…"},
        {"Create encrypted copy…", "创建加密副本…"}, {"Create decrypted copy…", "创建解密副本…"},
        {"Close", "关闭"}, {"Exit", "退出"}, {"Edit", "编辑"}, {"Undo", "撤销"},
        {"Redo", "重做"}, {"Insert blank page", "插入空白页"}, {"Delete page", "删除页面"},
        {"Import pages…", "导入页面…"}, {"Add text…", "添加文字…"}, {"Add image…", "添加图片…"},
        {"Move page up", "页面上移"}, {"Move page down", "页面下移"},
        {"Highlight selection", "高亮选区"}, {"Underline selection", "为选区加下划线"},
        {"Strike out selection", "为选区加删除线"}, {"Rectangle selection", "矩形批注"},
        {"Ellipse selection", "椭圆批注"},
        {"Ink", "手绘"},
        {"Move object to selection", "把对象移动到选区"},
        {"Resize object to selection", "把对象缩放到选区"},
        {"Delete object in selection", "删除选区中的对象"},
        {"Rotate left", "向左旋转"}, {"Rotate right", "向右旋转"},
        {"View", "视图"}, {"Zoom in", "放大"}, {"Zoom out", "缩小"},
        {"Actual size", "实际大小"}, {"Previous page", "上一页"}, {"Next page", "下一页"},
        {"Tools", "工具"}, {"Search", "搜索"}, {"Watermark", "水印"},
        {"Add text watermark", "添加文字水印"}, {"Scan watermarks", "扫描水印"},
        {"Add image watermark…", "添加图片水印…"}, {"Current page only", "仅当前页"},
        {"Remove selected", "移除所选"}, {"Redaction preview", "涂黑预览"},
        {"Apply redactions", "永久应用涂黑"}, {"Settings", "设置"},
        {"Select an object, then drag its destination", "先框选对象，再拖出目标位置"},
        {"Select an object, then drag its new bounds", "先框选对象，再拖出新的边界"},
        {"Mark content for permanent redaction", "标记需要永久涂黑的内容"},
        {"Permanently remove marked content", "永久移除已标记的内容"},
        {"Search document text and press Enter", "搜索文档文字并按 Enter"},
        {"Main toolbar", "主工具栏"}, {"Edit toolbar", "编辑工具栏"},
        {"Language", "语言"}, {"English", "English"}, {"简体中文", "简体中文"},
        {"Help", "帮助"}, {"About nexPDF", "关于 nexPDF"},
        {"Open a PDF to begin", "打开 PDF 以开始"}, {"Page", "页码"}, {"of", "/"},
        {"Watermark text", "水印文字"}, {"Opacity", "透明度"}, {"Rotation", "旋转角度"},
        {"Scale", "缩放"}, {"Foreground", "前景"}, {"Background", "背景"},
        {"Page range", "页码范围"}, {"Layer", "层级"}, {"Position", "位置"},
        {"Example: 1-3,5; empty means all", "示例：1-3,5；留空表示全部页面"},
        {"Top left", "左上"}, {"Top center", "上中"}, {"Top right", "右上"},
        {"Center left", "左中"}, {"Center", "居中"}, {"Center right", "右中"},
        {"Bottom left", "左下"}, {"Bottom center", "下中"}, {"Bottom right", "右下"},
        {"All pages", "所有页面"},
        {"Password required", "需要密码"}, {"Enter the PDF password:", "请输入 PDF 密码："},
        {"Open PDF", "打开 PDF"}, {"PDF files (*.pdf)", "PDF 文件 (*.pdf)"},
        {"Save PDF", "保存 PDF"}, {"Replace file?", "替换文件？"},
        {"The destination exists. Replace it?", "目标文件已存在，是否替换？"},
        {"Object selected. Drag the destination rectangle.", "已选择对象，请拖出目标位置和大小。"},
        {"Signed document", "已签名文档"},
        {"Editing this document invalidates its digital signatures. It must be saved to a new file.",
         "修改此文档会使数字签名失效，必须另存为新文件。"},
        {"User password", "用户密码"}, {"Owner password", "所有者密码"},
        {"AES-256", "AES-256"}, {"AES-128 compatibility", "AES-128 兼容模式"},
        {"Allow printing", "允许打印"}, {"Allow copying", "允许复制"},
        {"Allow annotations", "允许批注"}, {"Allow form filling", "允许填写表单"},
        {"Allow page assembly", "允许页面编排"}, {"Allow modification", "允许修改"},
        {"Allow accessibility extraction", "允许无障碍提取"},
        {"Allow high-quality printing", "允许高质量打印"},
        {"An owner password is required.", "必须设置所有者密码。"},
        {"Create encrypted copy", "创建加密副本"}, {"Passwords do not match", "密码不匹配"},
        {"Remove encryption", "移除加密"},
        {"PDF permissions rely on reader cooperation and are not a substitute for access control.",
         "PDF 权限依赖阅读器遵守，不能替代真正的访问控制。"},
        {"Error", "错误"}, {"Details", "详细信息"}, {"Ready", "就绪"},
        {"No watermark candidates were found.", "未发现水印候选。"},
        {"Review every candidate before removal. External baked-in watermarks may not be detected safely.",
         "移除前请逐项检查。外部烘焙水印可能无法被安全识别。"},
        {"Add a removable text watermark", "添加可精确移除的文字水印"},
        {"Add a removable image watermark", "添加可精确移除的图片水印"},
        {"Find removable watermark candidates", "查找可移除的水印候选"},
        {"Remove only the checked candidates", "仅移除已勾选的候选项"},
        {"Permanent redaction", "永久涂黑"},
        {"Applying redactions permanently removes overlapping content. Continue?",
         "应用涂黑会永久移除重叠内容，是否继续？"},
        {"About nexPDF", "关于 nexPDF"},
        {"nexPDF %1\nLocal PDF processing with no telemetry or document upload.\nLicensed under AGPL-3.0-or-later.",
         "nexPDF %1\n本地处理 PDF，无遥测、无文档上传。\n采用 AGPL-3.0-or-later 许可。"},
        {"Open a PDF first.", "请先打开 PDF。"},
        {"The PDF engine is not available.", "PDF 引擎不可用。"},
        {"The selected PDF does not exist.", "所选 PDF 不存在。"},
        {"Unable to open the PDF.", "无法打开 PDF。"},
        {"The password is incorrect.", "密码错误。"},
        {"Unable to render the page.", "无法渲染页面。"},
        {"The edit could not be applied.", "无法应用编辑。"},
        {"The watermark could not be added.", "无法添加水印。"},
        {"Watermark text cannot be empty.", "水印文字不能为空。"},
        {"The watermark image does not exist.", "水印图片不存在。"},
        {"The watermark image format is not supported.", "不支持此水印图片格式。"},
        {"The watermark image could not be prepared.", "无法准备水印图片。"},
        {"The watermark page range is invalid.", "水印页码范围无效。"},
        {"nexPDF watermark", "nexPDF 水印"},
        {"Watermark annotation", "水印批注"},
        {"Repeated page-content image", "跨页重复正文图片"},
        {"Repeated page-content text: %1", "跨页重复正文文字：%1"},
        {"This watermark cannot be isolated safely.", "无法安全隔离此水印。"},
        {"A selected watermark candidate is no longer valid.", "所选水印候选已失效。"},
        {"Watermark scanning failed.", "水印扫描失败。"},
        {"The confirmed watermarks could not be removed.", "无法移除已确认的水印。"},
        {"The PDF could not be written.", "无法写入 PDF。"},
        {"The temporary PDF failed reopen validation.", "临时 PDF 重新打开校验失败。"},
        {"Unable to initialize the PDF engine.", "无法初始化 PDF 引擎。"},
        {"The render request is outside the document.", "渲染请求超出文档范围。"},
        {"A render tile cannot be larger than 1024 pixels per edge.", "渲染瓦片单边不能超过 1024 像素。"},
        {"Text search failed.", "文本搜索失败。"},
        {"The selected page does not exist.", "所选页面不存在。"},
        {"Text selection failed.", "文本选择失败。"},
        {"No text in selection", "选区内没有文字"},
        {"Selected text copied to clipboard", "所选文字已复制到剪贴板"},
        {"This document does not grant editing permission.", "此文档未授予编辑权限。"},
        {"Choose a valid destination file.", "请选择有效的目标文件。"},
        {"A signed PDF must be saved to a different file because editing invalidates signatures.",
         "编辑会使签名失效，已签名 PDF 必须保存到其他文件。"},
        {"Confirm before replacing an existing file.", "替换已有文件前必须确认。"},
        {"The destination directory cannot be created.", "无法创建目标目录。"},
        {"A temporary file cannot be created beside the destination.", "无法在目标文件旁创建临时文件。"},
        {"Passwords must be shorter than 128 UTF-8 bytes.", "密码的 UTF-8 长度必须小于 128 字节。"},
        {"The validated temporary file could not replace the destination.", "已校验临时文件无法替换目标文件。"},
        {"Undo failed.", "撤销失败。"}, {"Redo failed.", "重做失败。"},
        {"The document has unsaved changes.", "文档包含未保存的修改。"}
    };
    for (const auto &[english, chinese] : entries) {
        translations_.insert(QString::fromUtf8(english), QString::fromUtf8(chinese));
    }
}

QString AppTranslator::translate(const char *, const char *sourceText, const char *, int) const
{
    return translations_.value(QString::fromUtf8(sourceText));
}
